title: "via_maximus"
description: "an engineering log"
url: "https://viamaximus.com"
baseurl: ""
timezone: America/New_York

remote_theme: "viamaximus/windows-95@ae9d8e2"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

permalink: /:categories/:year/:month/:day/:title/

exclude:
  - vendor/
  - .gem/
  - .direnv/
  - .jekyll-cache/
  - node_modules/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
