title: "via_maximus"
description: "an engineering log"
url: "http://127.0.0.1:4000"   # will change to https://viamaximus.com later
timezone: America/New_York

remote_theme: "viamaximus/windows-95"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

permalink: /:categories/:year/:month/:day/:title/

exclude:
  - vendor/
  - .gem/
  - .direnv/
  - .jekyll-cache/
  - node_modules/

